name: CI
on: [pull_request, push]
jobs:
  mix_test:
    name: mix test (Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }})
    strategy:
      matrix:
        elixir: ["1.7.4", "1.10.1"]
        include:
          - elixir: "1.7.4"
            otp: "19.x"
          - elixir: "1.10.1"
            otp: "22.x"
    runs-on: ubuntu-18.04
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql db: ex_sieve_test
          postgresql user: ex_sieve_user
          postgresql password: ex_sieve_password
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: Install Dependencies
        run: mix deps.get
      - name: Run Tests
        run: mix ecto.migrate && mix coveralls.github
        env:
          DB_USER: ex_sieve_user
          DB_PASSWORD: ex_sieve_password
